### ISSUE TITLE
Add support for RWMutex profiling

### ISSUE THREAD

**Issue by leearmstrong** [stackimpact/stackimpact-go#10]
I know this was only just released in Go 1.11 but is this on the roadmap?

**Comment by dmelikyan** [comment]
Yes, it is. It will be a separate profile or, alternatively, RWMutex nodes will be filterable (using metadata) in the existing blocking call profiles.

**Comment by dmelikyan** [comment]
Sorry for not providing any updates on this issue. Unfortunately we haven't got to implementing it yet. Can you give us a little bit more context on why you would prefer a separate RWMutex profile? The lock waiting should be reflected in the block profile (Time profile) already. Is there a case where it's not sufficient? Thanks!
