### ISSUE TITLE
Support Go modules

### ISSUE THREAD

**Issue by leearmstrong** [stackimpact/stackimpact-go#11]
We will be adopting Modules with 1.13 and have seen that when importing stackimpact-go it is marked as "incompatible".  It still works but I think something needs to be done on the stackimpact-go repo.

https://github.com/golang/go/wiki/Modules#how-are-versions-marked-as-incompatible

**Comment by kartavya-ramnani** [comment]
No Replies here..
And I think this is a valid issue.

Has stackimpact given up on golang services and customers ?
