### ISSUE TITLE
what do you mean "DEPRECATED" ?

### ISSUE THREAD

**Issue by batara666** [stackimpact/stackimpact-go#12]
DEPRECATED StackImpact Go Profiler - Production-Grade Performance Profiler: CPU, memory allocations, blocking calls, errors, metrics, and more

**Comment by pijng** [comment]
@batara666 If I understand correctly, it's all about StackImpact being acquired by Instana, Inc back in December 2019.
Now they're fully focused on developing and maintaining Instana's AutoProfile product.

"DEPRECATED" means "no longer maintained" in this context. You can see such a prefix at the beginning of every StackImpact's profiling packages on github.

Despite the stackimpact-go might work at the moment, it will face it's end-of-life at August 31, this year.

You can read more at their [blog post](https://stackimpact.com/blog/stackimpact-product-phase-out/).
