### ISSUE TITLE
Don't see stackimpact.Options() and 

### ISSUE THREAD

**Issue by dhbarman** [stackimpact/stackimpact-go#3]
I am using one agent and I can see the updates in the dashboard. I can use the following APIs:
 
agent := stackimpact.NewAgent()
agent.Configure("key", "MyGoApp")

But I am not able to use other APIs as mentioned in the examples such as:

stackimpact.Options() or agent.Start()

segment := agent.MeasureSegment("Segment1")
defer segment.Stop()

subsegment := agent.MeasureSubsegment("Segment1", "Subsegment1")
defer subsegment.Stop()

**Comment by dmelikyan** [comment]
Looks like it's just a version problem. Did you update to latest? Please check if you have 1.2.1. Version number can be found in debug logs or internal/agent.go in your app's packages.

**Comment by dhbarman** [comment]
I have updated to version 1.2.1. Now I can see the options. Thanks.
