### ISSUE TITLE
defer in loops

### ISSUE THREAD

**Issue by mikhailv** [stackimpact/stackimpact-go#4]
Hi, I have found at least two places in project where `defer` called in loop. To me, it is suspicious, and can be reason of non needed memory allocation. Maybe I'm wrong?

1. [/internal/message_queue.go#L39](https://github.com/stackimpact/stackimpact-go/blob/32a1f1725382d16282e21e3b67f9025f576f7d81/internal/message_queue.go#L39)
2. [/internal/config_loader.go#L31](https://github.com/stackimpact/stackimpact-go/blob/32a1f1725382d16282e21e3b67f9025f576f7d81/internal/config_loader.go#L31)

**Comment by dmelikyan** [comment]
Should be moved out of the loops in any case. Thanks for reporting this. It will be fixed in v1.4.1.
