### ISSUE TITLE
Looks like AutoProfiling option is not using by Agent

### ISSUE THREAD

**Issue by amsokol** [stackimpact/stackimpact-go#7]
Hi,

func (a *Agent) Start(options Options) does not use Options.AutoProfiling value.
Does it mean Options.AutoProfiling option is not supported any more?

**Comment by dmelikyan** [comment]
Thanks for pointing it out. It is possible now (latest agent version) to disable auto profiling, which is the default behaviour. The option is now called `DisableAutoProfiling`. 

Please note that `DisableAutoProfiling: true` should be used in rare cases when no timers are possible, for example a process freezes from time to time, e.g. on AWS Lambda.
