### ISSUE TITLE
agent not working inside a container

### ISSUE THREAD

**Issue by wrfly** [stackimpact/stackimpact-go#9]
I have a simple application using stackimpact agent for testing, but it can't work when I run this app inside a container.
I found that the api address is `agent-api.stackimpact.com` and I use`tcpdump` to capture the packets but they are all encrypted, but I did see the traffic.

That's the simple program:
```go
package main

import (
	"fmt"
	"net/http"

	"github.com/stackimpact/stackimpact-go"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello world!")
}

func main() {
	go func() {
		agent := stackimpact.Start(stackimpact.Options{
			AgentKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			AppName:  "hello-world-00",
		})
		span := agent.Profile()
		defer span.Stop()
	}()

	http.HandleFunc("/", handler)
	http.ListenAndServe(":8077", nil)
}
```

Is there anything I missed?

![image](https://user-images.githubusercontent.com/7827389/39300640-f6937882-497e-11e8-83ed-5ade88866639.png)

**Comment by dmelikyan** [comment]
The proper way to initialize the agent and use [focused profiling](https://stackimpact.com/docs/go-profiling/#focused-profiling) in your case would be:

```
package main

import (
	"fmt"
	"net/http"

	"github.com/stackimpact/stackimpact-go"
)

var agent *stackimpact.Agent

func handler(w http.ResponseWriter, r *http.Request) {
	span := agent.Profile()
	defer span.Stop()

	fmt.Fprintf(w, "Hello world!")
}

func main() {
	agent := stackimpact.Start(stackimpact.Options{
		AgentKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		AppName:  "hello-world-00",
	})

	http.HandleFunc("/", handler)
	http.ListenAndServe(":8077", nil)
}
```

If this app has some load you should see something in the profiles. Otherwise you may simulate some work in your handlers to see non-empty profiles.

**Comment by wrfly** [comment]
Hello, thanks for your reply. I still can't get data when the application is running in a docker container. I copied your code and changed the `AgentKey`.

The dockerfile is:

```dockerfile
FROM ubuntu:14.04
COPY stackimpact /usr/local/bin
CMD stackimpact
```

And I use these commands to build and run this image:

```bash
docker build -t stackimpact .
docker run --privileged --rm -ti -p 8077:8077 stackimpact
```

For simulating work load:
```
while true;do curl localhost:8077; sleep 1;done
```

**Comment by dmelikyan** [comment]
There shouldn't be any difference for the agent whether it is in the container or not. Could you add `Debug: true` to the startup options to see if there are any errors in the logs (it outputs to stdout by default)? Also, does the container have access to the internet? Thanks.

**Comment by wrfly** [comment]
```

**Comment by wrfly** [comment]
Fixed it by installing `ca-certificates`:

```dockerfile
RUN apt-get update
RUN apt-get install -y ca-certificates
```

Thanks bro.
